require "user.launch"
require "user.options"
require "user.keymaps"
spec "user.colorscheme"
spec "user.treesitter"
spec "user.devicons"
spec "user.mason"
spec "user.nvim-tree"
require "user.cmp"
-- require "user.lsp"
require "user.telescope"
require "user.autopairs"
require "user.rainbow"
require "user.gitsigns"
require "user.bufferline"
require "user.which-key"
require "user.toggleterm"
require "user.plugins"
